version: '3'
services:

  mi-scale:
    container_name: mi-scale
    image: lolouk44/xiaomi-mi-scale
    volumes:
      - /home/pi/xiaomi_mi_scale:/data
    privileged: true
    network_mode: host
    environment:
      - TZ=${TZ}
    restart: always

  switchbot-mqtt:
    container_name: switchbot-mqtt
    image: fphammerle/switchbot-mqtt:3.1.0-armv7
    network_mode: host
    userns_mode: host
    cap_add:
      - NET_ADMIN
    cap_drop:
      - ALL
    user: '0'
    environment:
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - FETCH_DEVICE_INFO=yes
    restart: always

    # PermissionError: [Errno 1] Operation not permitted
    # https://packages.debian.org/sid/libseccomp2
    # wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.2-2_armhf.deb
    # sudo dpkg -i libseccomp2_2.5.2-2_armhf.deb
